### ISSUE TITLE
CommandRunner

### ISSUE THREAD

**Issue by bidasknakayama** [IanSavchenko/BleLab#1]
Hello Ian

First, Sorry. This is not bug report. I need your advice about "CommandRunner".
https://github.com/IanSavchenko/BleLab/blob/master/BleLab/Commands/CommandRunner.cs

This class can start Task one by one.  It's good system : )
I need your advice ,

How to modify the "CommandRunner" to start new task after previous task finished ?
Do you have any idea ? 
I tried many try & error.. but I could not modify it like what I need....

Could you help me a bit ?

Kazu, Japan.

**Comment by IanSavchenko** [comment]
Hi Kazu,

Thanks for your interest.
CommandRunner is in fact already doing what you asked. You can queue multiple commands into it and all of them will be run one by one. To queue one command after another particular one you have a number of options:

1. Subscribe to `Completed` event and push new command to `CommandRunner` in event handler like this

```
            var firstCommand = new ListDevicesCommand();
            var secondCommand = new ListDevicesCommand();
            firstCommand.Completed += (sender, args) =>
            {
                if (firstCommand.Status == CommandStatus.Succeeded)
                {
                    _commandRunner.EnqueueCommand(secondCommand);
                }
            };

            _commandRunner.EnqueueCommand(firstCommand);
```
2. Add a continuation for `Completed` task which you can obtain with `GetCompletedTask` extension method.

```
            var firstCommand = new ListDevicesCommand();
            var secondCommand = new ListDevicesCommand();
            firstCommand.GetCompletedTask().ContinueWith(task =>
            {
                if (firstCommand.Status == CommandStatus.Succeeded)
                {
                    _commandRunner.EnqueueCommand(secondCommand);
                }
            };

            _commandRunner.EnqueueCommand(firstCommand);
```

Didn't actually try to run these options, but I believe that something like this should work. If it doesn't or it's not what you meant, please, let me know.

**Comment by bidasknakayama** [comment]
Thank you for helping, Ian : )

if Task is few, Your idea is enough. 
I want to use your CommandRunner to connect a Hardware device. To avoid to multiple access to Hardware,  I want to use Queue. Then, I need to modify CommandRunner itself.

Yesterday, I tried to modify CommandRunner for 12 hours.. 
and Now I finished : )

**[Modified point]**
- Instead of Monitor.TryEnter, I use await _semaphores.WaitAsync(); to lock in Async method.
- EnqueueCommand has 2 new options. RunAwait = true mean Run one after other finished.
- Timeout_mSec can cancel a command after ____ m second.

I tested. it look like good.. but to use new CommandRunner.  
We need to modify "CommandBase.ExecuteAsync" to pass CancellationToken for timeout.

**but There is one problem..**
await Execute.OnUIThreadAsync(async () =>.....
I expect to wait Task.. but This line execute in a second... strange...

When command.RunOnUiThread=false -> work fine.
when command.RunOnUiThread=true --> not execute task one after other....

but this maybe problem of Calibrun.Micro itself.( [I posted a request](https://github.com/Caliburn-Micro/Caliburn.Micro/issues/477) )


Thank you !


`
 namespace BleLab.Commands
{
    public class CommandRunnerAwait
    {
        private readonly ConcurrentQueue<CommandBase> _commands = new ConcurrentQueue<CommandBase>();
        private SemaphoreSlim _semaphores = new SemaphoreSlim(1);
        public event EventHandler<CommandRunnerEvent> CommandEnqueued;
        public event EventHandler<CommandRunnerEvent> CommandDispatched;
        public event EventHandler<CommandRunnerEvent> CommandExecuted; 

        public async Task<T> EnqueueCommand<T>(T command, bool RunAwait = false, int Timeout_mSec = 5000) 
            where T : CommandBase
        {

            _commands.Enqueue(command);
            CommandEnqueued?.Invoke(this, new CommandRunnerEvent(command));
            DispatchNext(RunAwait, Timeout_mSec);

            return command;
        }

        private async Task DispatchNext(bool RunAwait, int Timeout_mSec)
        {
            if (_commands.Count == 0)
                return;

            await _semaphores.WaitAsync();

            try
            {
                CommandBase command;
                if (_commands.TryDequeue(out command))
                {
                    await Dispatch(command, RunAwait, Timeout_mSec);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"CommandRunner/DispatchNext/_semaphores/{ex.Message}");
            }
            finally
            {
                _semaphores.Release();
            }

            
        }

        private async Task Dispatch(CommandBase command, bool RunAwait, int Timeout_mSec)
        {
            if (RunAwait)
            {
                if (command.RunOnUiThread)
                    await Execute.OnUIThreadAsync(async () => await ExecuteAndDispatchNext(command, RunAwait, Timeout_mSec));
                else
                    await Task.Run(async () => await ExecuteAndDispatchNext(command, RunAwait, Timeout_mSec));
            }
            else
            {
                if (command.RunOnUiThread)
                    Execute.OnUIThreadAsync(async () => await ExecuteAndDispatchNext(command, RunAwait, Timeout_mSec));
                else
                    Task.Run(async () => await ExecuteAndDispatchNext(command, RunAwait, Timeout_mSec));
            }
            CommandDispatched?.Invoke(this, new CommandRunnerEvent(command));
        }

        private async Task ExecuteAndDispatchNext(CommandBase command, bool RunAwait, int Timeout_mSec)
        {
            // Instantiate the CancellationTokenSource.
            var cts = new CancellationTokenSource();
            cts.CancelAfter(Timeout_mSec);

            // To run this. We have to modify CommandBase...
            await command.ExecuteAsync(cts.Token).ConfigureAwait(false);

            CommandExecuted?.Invoke(this, new CommandRunnerEvent(command));

            DispatchNext(RunAwait, Timeout_mSec);
        }
    }
}`

**Comment by IanSavchenko** [comment]
Hi Kazu,

Sorry for long delay, was a bit busy.

You are absolutely right, there were some flaws in CommandRunner design. I was a bit in a hurry when writing it. Now I pushed changes to master along with tests which should make sure that commands are executed sequentially. 

I can tell you that in your example above Semaphore won't help in case when `RunAwait == false`. I would say even more on that: having `RunAwait = false` will never tell you when command finished execution unless you attach a task with `ContinueWith`. That's why in my solution I will be `await`ing for a command to finish. 

Also, I saw that you are interested in cancellations and timeouts for commands. I implemented that on a separate branch as an exercise, because don't really see now where it can be used in the app. So it will leave in a branch for now unless there will be a good place to use it. One important thing I have to mention is that both cancellation and timeout are part of a command, not a runner interface. That's why you will find it in a separate base class for commands. This can be useful for scenarios when you want to have a default timeout for a particular command or a group of commands. 

We can continue discussing this if you are interested. Thanks again for your findings!

**Comment by bidasknakayama** [comment]
Thank you , Ian.
I really have interest in your new code !
Now I am a bit busy with other project, 
I am really want to do test it after current project.
and.
Your code help me lot to understand Caliburn.Micro !
it is best example of Caliburn.Micro : )
Now, With your Blelab, Caliburn micro is my favorite framework. hehe

Kazu

**Comment by bidasknakayama** [comment]
I'm back. Again : )

I tested your New CommandRunnder. ( sorry for long time ).
Here is test result . Below is my test command.

` // Click it
private async void ClickTest01(){

            // Prepare
            var command1 = new TestCommand
            {
                RunOnUiThread = false,
                ExecuteAction = async () => {
                    Debug.WriteLine($"1-start");
                    await Task.Delay(2000);
                    Debug.WriteLine($"1-end");
                }
            };
            var command2 = new TestCommand
            {
                RunOnUiThread = false,
                ExecuteAction = async () => {
                    Debug.WriteLine($"2-start");
                    await Task.Delay(2000);
                    Debug.WriteLine($"2-end");
                }
            };
            var command3 = new TestCommand
            {
                RunOnUiThread = false,
                ExecuteAction = async () => {
                    Debug.WriteLine($"3-start");
                    await Task.Delay(2000);
                    Debug.WriteLine($"3-end");
                }
            };

            // Execute
            Debug.WriteLine($"1-Enqueue");
            var result = _commandRunner.Enqueue(command1).AsTask().ConfigureAwait(true);
            Debug.WriteLine($"2-Enqueue");
            result = _commandRunner.Enqueue(command2).AsTask().ConfigureAwait(true);
            Debug.WriteLine($"3-Enqueue");
            result = _commandRunner.Enqueue(command3).AsTask().ConfigureAwait(true);
        }`

Here is result. First CommandRunner enqueue 3 pics. and execute at same time. but This is not my need. I want to use CommandRunnder to access a Serial line. I want to run FIFO. each by each. 

`1-Enqueue
1-start
2-Enqueue
3-Enqueue
2-start
3-start
1-end
2-end
3-end`


I modified 2 point.

**Point #1**

in [TestCommand.cs](https://github.com/IanSavchenko/BleLab/blob/master/BleLab.Tests/Commands/TestCommand.cs), I change to "Func\<Task\>" to "await".

` public Func\<Task\> ExecuteAction { get; set; }

//public System.Action ExecuteAction { get; set; }`
        
**Point #2**

in [TestCommand.cs](https://github.com/IanSavchenko/BleLab/blob/master/BleLab.Tests/Commands/TestCommand.cs), in DoExecuteAsync, I added "await".

` protected override async Task DoExecuteAsync()
        {
            //ExecuteAction?.Invoke();

            var result = ExecuteAction?.Invoke();
            await result;


        }`

after this modification, Execution result is below.

`1-Enqueue
1-start
2-Enqueue
3-Enqueue
1-end
2-start
2-end
3-start
3-end`
  
This is good result for me. because I have 1 serial COM Port. I only allow to access 1 queue-command at same time. After first queue is finish, I want to run 2nd queue.

thank you !
