### ISSUE TITLE
Greetings from China 

### ISSUE THREAD

**Issue by liuxingmoyi** [IanSavchenko/BleLab#2]
Hello guys !

How are you !     Have you released the apps named "Blelab" to Git hub web site below : https://github.com/IanSavchenko/BleLab ？👍 

Excuse me ！I'm a EE RD from China , and I have got some troubles with using it , could you  please reply to help me?

Give me your email please , if possibly  ? It will be really helpfull ! 
This's my personal email : liuxingmoyi@163.com , thank you very much all the same ！

**Comment by IanSavchenko** [comment]
Sure, you can ask, I replied to your email. But it's better to do in the GitHub issue you created, so other people might see the problem and solution.

**Comment by liuxingmoyi** [comment]
I can't send you the picture with this. Please check the emails again .
